# Generated by Django 3.2 on 2024-03-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('Основы бизнеса и предпринимательства', 'Основы бизнеса и предпринимательства'), ('Цифровой маркетинг и реклама в Интернете', 'Цифровой маркетинг и реклама в Интернете'), ('Финансовый рынок и инвестиционные стратегии', 'Финансовый рынок и инвестиционные стратегии'), ('Искусство цвета и композиции', 'Искусство цвета и композиции'), ('Python для начинающих', 'Python для начинающих'), ('Французский язык и культура', 'Французский язык и культура'), ('Психология управления временем и эффективности', 'Психология управления временем и эффективности')], max_length=128, verbose_name='Название курса')),
                ('contact', models.CharField(max_length=128, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('status', models.CharField(choices=[('a', 'В обработке'), ('b', 'Выполнено'), ('c', 'Отклонено')], max_length=100, verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
