# Generated by Django 3.2 on 2024-03-31 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_video'),
        ('appeal', '0002_auto_20240325_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appeal',
            name='seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appeal',
            name='events_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events', verbose_name='Название курса'),
        ),
    ]
