# Generated by Django 3.2 on 2024-03-31 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тематика',
                'verbose_name_plural': 'Тематики',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Названние')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='%Y/%m/%d', verbose_name='Изображение')),
                ('video', models.CharField(max_length=128, verbose_name='Видео')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('place', models.CharField(max_length=128, verbose_name='Место проведения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('seats', models.CharField(max_length=128, verbose_name='Количество мест')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.topic', verbose_name='Тематика')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
