# Generated by Django 3.2 on 2024-04-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_name',
        ),
    ]
