# Generated by Django 3.2 on 2024-03-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='video',
            field=models.CharField(max_length=128, verbose_name='Видео'),
        ),
    ]
