# Generated by Django 3.2 on 2024-04-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_booking_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
    ]
