# Generated by Django 5.0.4 on 2024-04-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('a', 'В обработке'), ('b', 'Выполнено'), ('c', 'Отклонено')], default='В обработке', max_length=100, verbose_name='Статус'),
        ),
    ]
