# Generated by Django 5.0.4 on 2024-04-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Выполнено', 'Выполнено'), ('Отклонено', 'Отклонено')], default='В обработке', max_length=100, verbose_name='Статус'),
        ),
    ]
