# Generated by Django 5.0.4 on 2024-04-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20240405_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='media/profile.png', upload_to='%Y/%m/%d'),
        ),
    ]
